av_metadata_conv is deprecated with lastest lavf

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1057,7 +1057,7 @@ if [ -n "$lavflibdir" ]; then
 fi
 
 echolog "Checking for libavformat ..."
-check_lib_pkgcfg libavformat libavformat/avformat.h av_metadata_conv -lavformat || die "Error, can't find libavformat !"
+check_lib_pkgcfg libavformat libavformat/avformat.h av_metadata_get -lavformat || die "Error, can't find libavformat !"
 
 
 #################################################
