fix check with pthread for Windows; based on a patch by Vincent Torri

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -946,11 +946,22 @@ check_cppflags -D_FILE_OFFSET_BITS=64
 check_cppflags -D_REENTRANT
 
 # default extralibs
-add_extralibs -lpthread && add_pkgconfig_libs -lpthread
 
 #################################################
 #   check for functions availability
 #################################################
+
+# pthread
+check_lib pthread.h pthread_mutex_init -lpthread
+if [ "$?" != 0 ]; then
+  check_lib pthread.h pthread_mutex_init -lpthreadGC2
+  [ "$?" != 0 ] && die "Error, can't find pthread_mutex_init !"
+  add_pkgconfig_libs -lpthreadGC2
+else
+  add_pkgconfig_libs -lpthread
+fi
+
+# clock_gettime
 check_lib time.h clock_gettime
 if [ "$?" != 0 ]; then
   check_lib time.h clock_gettime -lrt
